/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ConvertersRouteImport } from './routes/converters'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCategoryRouteImport } from './routes/c.$category'
import { Route as CCategoryIndexRouteImport } from './routes/c.$category.index'
import { Route as CCategoryPairRouteImport } from './routes/c.$category.$pair'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertersRoute = ConvertersRouteImport.update({
  id: '/converters',
  path: '/converters',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryIndexRoute = CCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CCategoryRoute,
} as any)
const CCategoryPairRoute = CCategoryPairRouteImport.update({
  id: '/$pair',
  path: '/$pair',
  getParentRoute: () => CCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/converters': typeof ConvertersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/c/$category': typeof CCategoryRouteWithChildren
  '/c/$category/$pair': typeof CCategoryPairRoute
  '/c/$category/': typeof CCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/converters': typeof ConvertersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/c/$category/$pair': typeof CCategoryPairRoute
  '/c/$category': typeof CCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/converters': typeof ConvertersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/c/$category': typeof CCategoryRouteWithChildren
  '/c/$category/$pair': typeof CCategoryPairRoute
  '/c/$category/': typeof CCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/converters'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/c/$category'
    | '/c/$category/$pair'
    | '/c/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/converters'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/c/$category/$pair'
    | '/c/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/converters'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/c/$category'
    | '/c/$category/$pair'
    | '/c/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConvertersRoute: typeof ConvertersRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CCategoryRoute: typeof CCategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converters': {
      id: '/converters'
      path: '/converters'
      fullPath: '/converters'
      preLoaderRoute: typeof ConvertersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category/': {
      id: '/c/$category/'
      path: '/'
      fullPath: '/c/$category/'
      preLoaderRoute: typeof CCategoryIndexRouteImport
      parentRoute: typeof CCategoryRoute
    }
    '/c/$category/$pair': {
      id: '/c/$category/$pair'
      path: '/$pair'
      fullPath: '/c/$category/$pair'
      preLoaderRoute: typeof CCategoryPairRouteImport
      parentRoute: typeof CCategoryRoute
    }
  }
}

interface CCategoryRouteChildren {
  CCategoryPairRoute: typeof CCategoryPairRoute
  CCategoryIndexRoute: typeof CCategoryIndexRoute
}

const CCategoryRouteChildren: CCategoryRouteChildren = {
  CCategoryPairRoute: CCategoryPairRoute,
  CCategoryIndexRoute: CCategoryIndexRoute,
}

const CCategoryRouteWithChildren = CCategoryRoute._addFileChildren(
  CCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConvertersRoute: ConvertersRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CCategoryRoute: CCategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
