// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/convert.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
import { CATEGORY_MAP, convert, formatResult } from "npm:@/lib/converters/data";
var convert_default = defineTool({
  name: "convert",
  title: "Convert a value between units",
  description: "Convert a numeric value from one unit to another within a category. Use category/unit IDs returned by `list_categories` and `list_units`. Example: category='length', from='ft', to='cm', value=5.917.",
  inputSchema: {
    category: z.string().describe("Category ID, e.g. 'length', 'temperature'."),
    from: z.string().describe("Source unit ID, e.g. 'ft'."),
    to: z.string().describe("Target unit ID, e.g. 'cm'."),
    value: z.number().finite().describe("Numeric value to convert.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, from, to, value }) => {
    const cat = CATEGORY_MAP[category];
    if (!cat) {
      return {
        content: [{ type: "text", text: `Unknown category '${category}'.` }],
        isError: true
      };
    }
    const fromUnit = cat.units.find((u) => u.id === from);
    const toUnit = cat.units.find((u) => u.id === to);
    if (!fromUnit || !toUnit) {
      return {
        content: [
          {
            type: "text",
            text: `Unknown unit in category '${category}': from='${from}' to='${to}'. Call list_units for valid IDs.`
          }
        ],
        isError: true
      };
    }
    const result = convert(cat, value, from, to);
    if (!Number.isFinite(result)) {
      return { content: [{ type: "text", text: "Conversion produced a non-finite result." }], isError: true };
    }
    const formatted = formatResult(result);
    const summary = `${formatResult(value)} ${fromUnit.symbol} = ${formatted} ${toUnit.symbol}`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        category: cat.id,
        from: { id: fromUnit.id, name: fromUnit.name, symbol: fromUnit.symbol },
        to: { id: toUnit.id, name: toUnit.name, symbol: toUnit.symbol },
        input: value,
        result,
        resultFormatted: formatted
      }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { CATEGORIES } from "npm:@/lib/converters/data";
import { GROUP_LABELS } from "npm:@/lib/converters/types";
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "List conversion categories",
  description: "List every supported unit-conversion category (length, weight, temperature, pressure, etc.) with its ID, name, group, and short description.",
  inputSchema: {
    group: z2.string().optional().describe(
      "Optional group filter: common, engineering, heat, fluids, light, electricity, magnetism, radiology, other."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ group }) => {
    const filtered = group ? CATEGORIES.filter((c) => c.group === group) : CATEGORIES;
    const items = filtered.map((c) => ({
      id: c.id,
      name: c.name,
      group: c.group,
      groupLabel: GROUP_LABELS[c.group],
      description: c.description,
      unitCount: c.units.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { categories: items, total: items.length }
    };
  }
});

// src/lib/mcp/tools/list-units.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { CATEGORY_MAP as CATEGORY_MAP2 } from "npm:@/lib/converters/data";
var list_units_default = defineTool3({
  name: "list_units",
  title: "List units in a category",
  description: "Return every unit available inside a conversion category. Use the category ID returned by `list_categories` (e.g. 'length', 'weight', 'pressure').",
  inputSchema: {
    category: z3.string().describe("Category ID, e.g. 'length', 'temperature', 'pressure'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const cat = CATEGORY_MAP2[category];
    if (!cat) {
      return {
        content: [{ type: "text", text: `Unknown category '${category}'. Call list_categories to see valid IDs.` }],
        isError: true
      };
    }
    const units = cat.units.map((u) => ({
      id: u.id,
      name: u.name,
      symbol: u.symbol,
      aliases: u.aliases ?? []
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ category: cat.id, baseUnit: cat.baseUnit, units }, null, 2) }],
      structuredContent: { category: cat.id, baseUnit: cat.baseUnit, units }
    };
  }
});

// src/lib/mcp/tools/parse-and-convert.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
import { parseConversionQuery } from "npm:@/lib/parseConversionQuery";
import { convert as convert2, formatResult as formatResult2 } from "npm:@/lib/converters/data";
var parse_and_convert_default = defineTool4({
  name: "parse_and_convert",
  title: "Parse a natural-language conversion",
  description: "Parse and evaluate a natural-language conversion query such as '5 ft 11 in to cm', '70 F in C', or '250 grams to ounces'. Returns the detected category, source/target units, and the converted value.",
  inputSchema: {
    query: z4.string().min(1).describe("Natural-language conversion query.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const parsed = parseConversionQuery(query);
    if (!parsed) {
      return {
        content: [
          {
            type: "text",
            text: `Could not parse '${query}'. Try formats like '5 km to miles' or '70 F in C'.`
          }
        ],
        isError: true
      };
    }
    const result = convert2(parsed.category, parsed.value, parsed.from.id, parsed.to.id);
    if (!Number.isFinite(result)) {
      return { content: [{ type: "text", text: "Conversion produced a non-finite result." }], isError: true };
    }
    const formatted = formatResult2(result);
    const summary = `${formatResult2(parsed.value)} ${parsed.from.symbol} = ${formatted} ${parsed.to.symbol}`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        query,
        category: parsed.category.id,
        from: { id: parsed.from.id, name: parsed.from.name, symbol: parsed.from.symbol },
        to: { id: parsed.to.id, name: parsed.to.name, symbol: parsed.to.symbol },
        input: parsed.value,
        result,
        resultFormatted: formatted
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "turbo-unit-converter-mcp",
  title: "Turbo Unit Converter",
  version: "0.1.0",
  instructions: "Precise unit conversion tools covering 75+ categories (length, weight, temperature, volume, pressure, energy, power, speed, data, and many engineering, heat, fluids, light, electricity, magnetism, and radiology categories). Use `list_categories` to discover categories, `list_units` for units in a category, `convert` to run a conversion by category/unit IDs, and `parse_and_convert` for natural-language queries like '5 ft 11 in to cm'.",
  tools: [convert_default, list_categories_default, list_units_default, parse_and_convert_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
